// <auto-generated />
namespace My_Personal_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class m11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m11));
        
        string IMigrationMetadata.Id
        {
            get { return "201808261524131_m11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
