//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Personal_Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My_Personal_Website.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an education qualification.
        /// </summary>
        public static string AddEdu {
            get {
                return ResourceManager.GetString("AddEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add experience.
        /// </summary>
        public static string AddExp {
            get {
                return ResourceManager.GetString("AddExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add language.
        /// </summary>
        public static string AddLang {
            get {
                return ResourceManager.GetString("AddLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add reference.
        /// </summary>
        public static string AddRef {
            get {
                return ResourceManager.GetString("AddRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add skill.
        /// </summary>
        public static string AddSkill {
            get {
                return ResourceManager.GetString("AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add training course.
        /// </summary>
        public static string AddTr {
            get {
                return ResourceManager.GetString("AddTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Options.
        /// </summary>
        public static string AdminOptions {
            get {
                return ResourceManager.GetString("AdminOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        public static string As {
            get {
                return ResourceManager.GetString("As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate image.
        /// </summary>
        public static string CertImage {
            get {
                return ResourceManager.GetString("CertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company website.
        /// </summary>
        public static string CmpyWebsite {
            get {
                return ResourceManager.GetString("CmpyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string CodePostal {
            get {
                return ResourceManager.GetString("CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        public static string ContactMe {
            get {
                return ResourceManager.GetString("ContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course date.
        /// </summary>
        public static string CourseDate {
            get {
                return ResourceManager.GetString("CourseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree image.
        /// </summary>
        public static string DegImg {
            get {
                return ResourceManager.GetString("DegImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed.
        /// </summary>
        public static string Developed {
            get {
                return ResourceManager.GetString("Developed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit.
        /// </summary>
        public static string Digit {
            get {
                return ResourceManager.GetString("Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string DT {
            get {
                return ResourceManager.GetString("DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit education qualification.
        /// </summary>
        public static string EditEdu {
            get {
                return ResourceManager.GetString("EditEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit experience.
        /// </summary>
        public static string EditExp {
            get {
                return ResourceManager.GetString("EditExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit language.
        /// </summary>
        public static string EditLang {
            get {
                return ResourceManager.GetString("EditLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit reference.
        /// </summary>
        public static string EditRef {
            get {
                return ResourceManager.GetString("EditRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit skill.
        /// </summary>
        public static string EditSkill {
            get {
                return ResourceManager.GetString("EditSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit training course.
        /// </summary>
        public static string EditTr {
            get {
                return ResourceManager.GetString("EditTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Experience.
        /// </summary>
        public static string ExpPro {
            get {
                return ResourceManager.GetString("ExpPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish date.
        /// </summary>
        public static string FinishDate {
            get {
                return ResourceManager.GetString("FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description.
        /// </summary>
        public static string JobDesc {
            get {
                return ResourceManager.GetString("JobDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening level.
        /// </summary>
        public static string LstLevel {
            get {
                return ResourceManager.GetString("LstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location link.
        /// </summary>
        public static string MapLink {
            get {
                return ResourceManager.GetString("MapLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message details.
        /// </summary>
        public static string MsgDetails {
            get {
                return ResourceManager.GetString("MsgDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text.
        /// </summary>
        public static string MsgText {
            get {
                return ResourceManager.GetString("MsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct online message.
        /// </summary>
        public static string OnlineMsg {
            get {
                return ResourceManager.GetString("OnlineMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNum {
            get {
                return ResourceManager.GetString("PhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project link.
        /// </summary>
        public static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectNAme {
            get {
                return ResourceManager.GetString("ProjectNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading level.
        /// </summary>
        public static string RdLevel {
            get {
                return ResourceManager.GetString("RdLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string Seen {
            get {
                return ResourceManager.GetString("Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show certificate.
        /// </summary>
        public static string ShowCertificate {
            get {
                return ResourceManager.GetString("ShowCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show degree.
        /// </summary>
        public static string ShowDegree {
            get {
                return ResourceManager.GetString("ShowDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill name.
        /// </summary>
        public static string SkillName {
            get {
                return ResourceManager.GetString("SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking.
        /// </summary>
        public static string Speaking {
            get {
                return ResourceManager.GetString("Speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking level.
        /// </summary>
        public static string SpkLevel {
            get {
                return ResourceManager.GetString("SpkLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        public static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block number.
        /// </summary>
        public static string StreetNo {
            get {
                return ResourceManager.GetString("StreetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Courses.
        /// </summary>
        public static string TrainingCourses {
            get {
                return ResourceManager.GetString("TrainingCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University website.
        /// </summary>
        public static string UniversityWebsite {
            get {
                return ResourceManager.GetString("UniversityWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display message.
        /// </summary>
        public static string ViewMsg {
            get {
                return ResourceManager.GetString("ViewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing level.
        /// </summary>
        public static string WrLevel {
            get {
                return ResourceManager.GetString("WrLevel", resourceCulture);
            }
        }
    }
}
